apiVersion: v1
kind: Namespace
metadata:
  name: edgetpu-demo
---
apiVersion: batch/v1
kind: Job
metadata:
  name: edgetpu-demo
  namespace: edgetpu-demo
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: edgetpu-demo
        image: ghcr.io/judahrand/edgetpu-demo:latest
        imagePullPolicy: Always
        args:
          - examples/classify_image.py \
          - --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite  \
          - --labels test_data/inat_bird_labels.txt \
          - --input test_data/parrot.jpg
        resources:
          limits:
            judahrand.org/edgetpu: 1
      restartPolicy: Never
